---

- name: Install all things defined in roles
  hosts: webserver
  user: horus
  become: yes
  become_method: sudo
  vars_files:
   - variables.yml
  tasks:

  roles:
#   - resolv 
#   - updateapt
#   - php
#   - sql
#   - sshd
